### ISSUE TITLE
有办法给同花顺的自选加备注信息吗？

### ISSUE THREAD

**Issue by reyoreyo** [misslng/10jqka#1]
有办法给同花顺的自选加备注信息吗？http://activity.10jqka.com.cn/acmake/cache/445.html?codelist=33:301038,&mode=num

**Comment by sbsbsbssbsbs** [comment]
简单看了一下
在网页的确认那里打断点,最后他数据整合完会进入cefApi这个js里调用同花顺本地的函数
http://s.thsi.cn/js/common/cefapi/1.3/cefApi.min.js
浏览器没有这些环境API.use就会为a.notClient && a.notClient()
我不是很懂cef,也许你可以再研究下

**Comment by reyoreyo** [comment]
方便加微信吗？我搞了半个月都没有搞定。可付费



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sbsbsbssbsbs ***@***.***&gt;
发送时间: 2023年10月30日 20:06
收件人: sbsbsbssbsbs/10jqka ***@***.***&gt;
抄送: reyoreyo ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sbsbsbssbsbs/10jqka] 有办法给同花顺的自选加备注信息吗？ (Issue #1)





 
简单看了一下
 在网页的确认那里打断点,最后他数据整合完会进入cefApi这个js里调用同花顺本地的函数
 http://s.thsi.cn/js/common/cefapi/1.3/cefApi.min.js
 浏览器没有这些环境API.use就会为a.notClient &amp;&amp; a.notClient()
 我不是很懂cef,也许你可以再研究下

**Comment by reyoreyo** [comment]
或者用你的方式试一下能修改自选的备注信息吗？

**Comment by sbsbsbssbsbs** [comment]
> 或者用你的方式试一下能修改自选的备注信息吗？

可以的

**Comment by reyoreyo** [comment]
写在你现有的系统中，预计什么时候可以搞定？方便加个联系方式吗？

**Comment by misslng** [comment]
> 写在你现有的系统中，预计什么时候可以搞定？方便加个联系方式吗？

不好意思啊,这个的进度应该要看什么时候有空了,快学期末了还有毕设,不是很有时间

**Comment by reyoreyo** [comment]
我可以付费帮忙搞一个成吗？或者帮忙找一个接口及参数给我也行，我自己提交参数
